from enum import Enum


class UraRoleList(Enum):
    UNKNOWN = 0
    DASHUKUAICHE = 1
    FUTEJIA = 2
    DAHECHIJI = 3
    TEBIEZHOU = 4
    SHENYING = 5
    MUBAILAIEN = 6
    DASHUKUAICHE_1 = 7
    FUTEJIA_1 = 8
    XIAOLIMAO = 9
    MUBAIMAIKUN = 10
    DONGHAIDIWANG = 11
    YOUXIUSUZHI = 12
    HUANGJINCHUAN = 13
    WANSHANSIJI = 14
    ZHONGPAO = 15
    SHENGLIJIANGQUAN = 16
    QICAO = 17
    CHAOJIXILIU = 18
    DONGHAIDIWANG_1 = 19
    MIYU = 20
    DAIJIANFULAI = 21
    SHENYING_1 = 22
    CAOSHANGFEI = 23
    YINGHUAJINWANG = 24
    WUSHENGLINGLU = 25
    CHUNWULALA = 26
    CAOSHANGFEI_1 = 27
    DIWANGGUANGHUI = 28
    DIWANGGUANGHUI_1 = 29
    QICAO_1 = 30
    CHUNWULALA_1 = 31
    AILISUZI = 32
    LUDAOFUXIANGZHENG = 33
    SHENGLIJIANGQUAN_1 = 34
    ZHONGPAO_1 = 35


class SupportCardType(Enum):
    SUPPORT_CARD_TYPE_UNKNOWN = 0
    SUPPORT_CARD_TYPE_SPEED = 1
    SUPPORT_CARD_TYPE_STAMINA = 2
    SUPPORT_CARD_TYPE_POWER = 3
    SUPPORT_CARD_TYPE_WILL = 4
    SUPPORT_CARD_TYPE_INTELLIGENCE = 5
    SUPPORT_CARD_TYPE_FRIEND = 6
    SUPPORT_CARD_TYPE_GROUP = 7
    SUPPORT_CARD_TYPE_NPC = 10


class SupportCardFavorLevel(Enum):
    SUPPORT_CARD_FAVOR_LEVEL_UNKNOWN = 0
    SUPPORT_CARD_FAVOR_LEVEL_1 = 1
    SUPPORT_CARD_FAVOR_LEVEL_2 = 2
    SUPPORT_CARD_FAVOR_LEVEL_3 = 3
    SUPPORT_CARD_FAVOR_LEVEL_4 = 4


class TrainingType(Enum):
    TRAINING_TYPE_UNKNOWN = 0
    TRAINING_TYPE_SPEED = 1
    TRAINING_TYPE_STAMINA = 2
    TRAINING_TYPE_POWER = 3
    TRAINING_TYPE_WILL = 4
    TRAINING_TYPE_INTELLIGENCE = 5


class MotivationLevel(Enum):
    MOTIVATION_LEVEL_UNKNOWN = 0
    MOTIVATION_LEVEL_1 = 1
    MOTIVATION_LEVEL_2 = 2
    MOTIVATION_LEVEL_3 = 3
    MOTIVATION_LEVEL_4 = 4
    MOTIVATION_LEVEL_5 = 5


class TurnOperationType(Enum):
    TURN_OPERATION_TYPE_UNKNOWN = 0
    TURN_OPERATION_TYPE_TRAINING = 1
    TURN_OPERATION_TYPE_REST = 2
    TURN_OPERATION_TYPE_MEDIC = 3
    TURN_OPERATION_TYPE_TRIP = 4
    TURN_OPERATION_TYPE_RACE = 5
