from bot.base.resource import Template

UMAMUSUME_UI_TEMPLATE_PATH = "/umamusume/ui"
UMAMUSUME_BTN_TEMPLATE_PATH = "/umamusume/btn"
UMAMUSUME_REF_TEMPLATE_PATH = "/umamusume/ref"
UMAMUSUME_UMA_ICON_TEMPLATE_PATH = "/umamusume/uma_icon"
UMAMUSUME_UMA_ROLE_TEMPLATE_PATH = "/umamusume/uma_role"

UI_MAIN_MENU = Template("MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MRT_MENU = Template("MRT_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMAS_MENU = Template("UMAS_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MRT_LIST = Template("MRT_LIST", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_1 = Template("UMA_DETAIL_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_2 = Template("UMA_DETAIL_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_2_JICHENG = Template("UMA_DETAIL_2_JICHENG", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_3 = Template("UMA_DETAIL_3", UMAMUSUME_UI_TEMPLATE_PATH)

UI_YINZIYILAN = Template("YINZIYILAN", UMAMUSUME_UI_TEMPLATE_PATH)

UI_UMA_BORROW = Template("UMA_BORROW", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_LIST_FINAL = Template("uma_list_final", UMAMUSUME_UI_TEMPLATE_PATH)

UI_PARENT_FACTOR_STAR = Template("PARENT_FACTOR_STAR", UMAMUSUME_REF_TEMPLATE_PATH)

# role
DASHUKUAICHE = Template("DASHUKUAICHE", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
FUTEJIA = Template("FUTEJIA", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DAHECHIJI = Template("DAHECHIJI", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DAHECHIJI_1 = Template("DAHECHIJI_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
TEBIEZHOU = Template("TEBIEZHOU", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
SHENYING = Template("SHENYING", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
MUBAILAIEN = Template("MUBAILAIEN", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
FUTEJIA_1 = Template("FUTEJIA_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
XIAOLIMAO = Template("XIAOLIMAO", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
MUBAIMAIKUN = Template("MUBAIMAIKUN", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DONGHAIDIWANG = Template("donghaidiwang", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
YOUXIUSUZHI = Template("youxiusuzhi", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
HUANGJINCHUAN = Template("HUANGJINCHUAN", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
WANSHANSIJI = Template("WANSHANSIJI", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
ZHONGPAO = Template("ZHONGPAO", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
SHENGLIJIANGQUAN = Template("SHENGLIJIANGQUAN", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
QICAO = Template("QICAO", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
CHAOJIXILIU = Template("CHAOJIXILIU", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DONGHAIDIWANG_1 = Template("DONGHAIDIWANG_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
MIYU = Template("MIYU", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DAIJIANFULAI = Template("DAIJIANFULAI", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
SHENYING_1 = Template("SHENYING_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
CAOSHANGFEI = Template("CAOSHANGFEI", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
YINGHUAJINWANG = Template("YINGHUAJINWANG", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
WUSHENGLINGLU = Template("WUSHENGLINGLU", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
CHUNWULALA = Template("CHUNWULALA", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
CAOSHANGFEI_1 = Template("CAOSHANGFEI_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DIWANGGUANGHUI = Template("DIWANGGUANGHUI", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
DIWANGGUANGHUI_1 = Template("DIWANGGUANGHUI_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
QICAO_1 = Template("QICAO_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
CHUNWULALA_1 = Template("CHUNWULALA_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
AILISUZI = Template("AILISUZI", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
LUDAOFUXIANGZHENG = Template("LUDAOFUXIANGZHENG", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
SHENGLIJIANGQUAN_1 = Template("SHENGLIJIANGQUAN_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)
ZHONGPAO_1 = Template("ZHONGPAO_1", UMAMUSUME_UMA_ROLE_TEMPLATE_PATH)

UMA_ROLE_LIST = [DASHUKUAICHE, FUTEJIA, DAHECHIJI, TEBIEZHOU, SHENYING, MUBAILAIEN, DAHECHIJI_1, FUTEJIA_1,
                 XIAOLIMAO, MUBAIMAIKUN, DONGHAIDIWANG, YOUXIUSUZHI, HUANGJINCHUAN, WANSHANSIJI, ZHONGPAO, SHENGLIJIANGQUAN, QICAO, CHAOJIXILIU,
                 DONGHAIDIWANG_1, MIYU, DAIJIANFULAI, SHENYING_1, CAOSHANGFEI, YINGHUAJINWANG, WUSHENGLINGLU, CHUNWULALA, CAOSHANGFEI_1,
                 DIWANGGUANGHUI_1, QICAO_1, CHUNWULALA_1, AILISUZI, LUDAOFUXIANGZHENG, SHENGLIJIANGQUAN_1, ZHONGPAO_1]
