from bot.base.resource import Template

UMAMUSUME_UI_TEMPLATE_PATH = "/umamusume/ui"
UMAMUSUME_BTN_TEMPLATE_PATH = "/umamusume/btn"
UMAMUSUME_REF_TEMPLATE_PATH = "/umamusume/ref"
UMAMUSUME_UMA_ICON_TEMPLATE_PATH = "/umamusume/uma_icon"

UI_MAIN_MENU = Template("MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MRT_MENU = Template("MRT_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMAS_MENU = Template("UMAS_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MRT_LIST = Template("MRT_LIST", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_1 = Template("UMA_DETAIL_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_2 = Template("UMA_DETAIL_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_2_JICHENG = Template("UMA_DETAIL_2_JICHENG", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_DETAIL_3 = Template("UMA_DETAIL_3", UMAMUSUME_UI_TEMPLATE_PATH)

UI_YINZIYILAN = Template("YINZIYILAN", UMAMUSUME_UI_TEMPLATE_PATH)

UI_UMA_BORROW = Template("UMA_BORROW", UMAMUSUME_UI_TEMPLATE_PATH)
UI_UMA_LIST_FINAL = Template("uma_list_final", UMAMUSUME_UI_TEMPLATE_PATH)
